export enum enCryptoSymbols {
    ETH_BTC = 'BINANCE:ETHBTC',
    VET_BTC = 'BINANCE:VETBTC',
    MATIC_BTC = 'BINANCE:MATICBTC',
    BNB_BTC = 'BINANCE:BNBBTC',
    FET_BTC = 'BINANCE:FETBTC',
    XRP_BTC = 'BINANCE:XRPBTC',
    LTC_BTC = 'BINANCE:LTCBTC',
    EOS_BTC = 'BINANCE:EOSBTC',
    LINK_BTC = 'BINANCE:LINKBTC',
    ONE_BTC = 'BINANCE:ONEBTC',
    BTC_USDT = 'BINANCE:BTCUSDT'
}